services:
  frontend:
    image: node:20
    container_name: frontend
    ports:
      - 80:3000
    working_dir: /srv/app
    command: "./setup.sh"
    volumes:
      - ./frontend:/srv/app
      - /srv/app/.next/
    tty: true

  backend:
    image: node:20
    container_name: backend
    ports:
      - 81:3000
    working_dir: /srv/app
    command: "./setup.sh"
    volumes:
      - ./backend:/srv/app
    tty: true

  database:
    image: mongo:6-jammy
    container_name: database
    ports:
      - 27017:27017
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6: